<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySystemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Mảng dữ liệu mẫu
        $data = [
            //Office type
            [
                'code_id' => 1,
                'code_name_en' => 'Headquarter',
                'code_name_tm' => 'தலைமை அலுவலகம்',
                'code_name_sn' => 'මූලස්ථානය',
                'module' => 'office_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Branch',
                'code_name_tm' => 'கிளை',
                'code_name_sn' => 'ශාඛාව',
                'module' => 'office_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Not applicable',
                'code_name_tm' => 'பொருந்தாது',
                'code_name_sn' => 'අදාළ නොවේ',
                'module' => 'office_type',
                'status' => 1,
            ],
            //TVET type
//            [
//                'code_id' => 1,
//                'code_name_en' => 'DTET',
//                'code_name_tm' => 'DTET',
//                'code_name_sn' => 'DTET',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 2,
//                'code_name_en' => 'NAITA',
//                'code_name_tm' => 'NAITA',
//                'code_name_sn' => 'NAITA',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 3,
//                'code_name_en' => 'VTA',
//                'code_name_tm' => 'VTA',
//                'code_name_sn' => 'VTA',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 4,
//                'code_name_en' => 'CoT (College of Technology)',
//                'code_name_tm' => 'CoT (College of Technology)',
//                'code_name_sn' => 'CoT (College of Technology)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 5,
//                'code_name_en' => 'TC (Technical College)',
//                'code_name_tm' => 'TC (Technical College)',
//                'code_name_sn' => 'TC (Technical College)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 6,
//                'code_name_en' => 'UC (UNIVOTEC and University Colleges)',
//                'code_name_tm' => 'UC (UNIVOTEC and University Colleges)',
//                'code_name_sn' => 'UC (UNIVOTEC and University Colleges)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 7,
//                'code_name_en' => 'DVTC (District Vocational Training Centers)',
//                'code_name_tm' => 'DVTC (District Vocational Training Centers)',
//                'code_name_sn' => 'DVTC (District Vocational Training Centers)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 8,
//                'code_name_en' => 'NVTI (National Vocational Training Institute)',
//                'code_name_tm' => 'NVTI (National Vocational Training Institute)',
//                'code_name_sn' => 'NVTI (National Vocational Training Institute)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 9,
//                'code_name_en' => 'VTC (Vocational Training Center)',
//                'code_name_tm' => 'VTC (Vocational Training Center)',
//                'code_name_sn' => 'VTC (Vocational Training Center)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 10,
//                'code_name_en' => 'Ocean University of Sri Lanka (OCUSL)',
//                'code_name_tm' => 'Ocean University of Sri Lanka (OCUSL)',
//                'code_name_sn' => 'Ocean University of Sri Lanka (OCUSL)',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 11,
//                'code_name_en' => 'Ceylon German Training Institute',
//                'code_name_tm' => 'Ceylon German Training Institute',
//                'code_name_sn' => 'Ceylon German Training Institute',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 12,
//                'code_name_en' => 'Sri Lanka – German Training Institute',
//                'code_name_tm' => 'Sri Lanka – German Training Institute',
//                'code_name_sn' => 'Sri Lanka – German Training Institute',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
//            [
//                'code_id' => 13,
//                'code_name_en' => 'National Youth Service Council',
//                'code_name_tm' => 'National Youth Service Council',
//                'code_name_sn' => 'National Youth Service Council',
//                'module' => 'tvet_type',
//                'status' => 1,
//            ],
            //Location of job
            [
                'code_id' => 1,
                'code_name_en' => 'Local',
                'code_name_tm' => 'உள்ளூர்',
                'code_name_sn' => 'දේශීය',
                'module' => 'job_location',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Foreign',
                'code_name_tm' => 'வெளியூர்',
                'code_name_sn' => 'විදේශීය',
                'module' => 'job_location',
                'status' => 1,
            ],
            //Company information
            [
                'code_id' => 1,
                'code_name_en' => 'Government',
                'code_name_tm' => 'அரச நிறுவகம்',
                'code_name_sn' => 'රාජ්‍ය',
                'module' => 'company_information',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Semi-Government / State-Owned Enterprise',
                'code_name_tm' => 'பகுதியான அரச நிறுவகம்',
                'code_name_sn' => 'අර්ධ රාජ්‍ය ',
                'module' => 'company_information',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Non-Government',
                'code_name_tm' => 'அரச சார்பற்ற நிறுவனம்',
                'code_name_sn' => 'රාජ්‍ය නොවන',
                'module' => 'company_information',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Private Limited Company',
                'code_name_tm' => 'பிரைவேட் லிமிடெட் கம்பனி',
                'code_name_sn' => 'පුද්ගලික සීමාසහිත සමාගම',
                'module' => 'company_information',
                'status' => 1,
            ],
            [
                'code_id' => 5,
                'code_name_en' => 'Private / Individual Business',
                'code_name_tm' => 'தனியார்',
                'code_name_sn' => 'පෞද්ගලික',
                'module' => 'company_information',
                'status' => 1,
            ],

            [
                'code_id' => 6,
                'code_name_en' => 'Other Organisation',
                'code_name_tm' => 'மற்றவை',
                'code_name_sn' => 'වෙනත්',
                'module' => 'company_information',
                'status' => 1,
            ],

            [
                'code_id' => 7,
                'code_name_en' => 'Public Limited Company',
                'code_name_tm' => 'பொது லிமிடெட் நிறுவனம்',
                'code_name_sn' => 'පොදු සීමිත සමාගම',
                'module' => 'company_information',
                'status' => 1,
            ],

            //Counselling title
            [
                'code_id' => 1,
                'code_name_en' => 'Counseling service',
                'code_name_tm' => 'ஆலோசனை சேவை',
                'code_name_sn' => 'උපදේශන සේවාව',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Skills Development and Upgrade',
                'code_name_tm' => 'திறன் மேம்பாடு மற்றும் மேம்படுத்தல்',
                'code_name_sn' => 'නිපුණතා සංවර්ධනය සහ වැඩිදියුණු කිරීම',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Vocational Training',
                'code_name_tm' => 'தொழில் பயிற்சி',
                'code_name_sn' => 'වෘත්තීය පුහුණුව',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Higher Education',
                'code_name_tm' => 'உயர் கல்வி',
                'code_name_sn' => 'උසස් අධ්‍යාපනය',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 5,
                'code_name_en' => 'RPL(Recognition of Prior Learning)',
                'code_name_tm' => 'RPL(முன் கற்றலின் அங்கீகாரம்)',
                'code_name_sn' => 'RPL (පෙර ඉගෙනීම පිළිගැනීම)',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 6,
                'code_name_en' => 'Gap filling',
                'code_name_tm' => 'இடைவெளி நிரப்புதல்',
                'code_name_sn' => 'හිඩැස් පිරවීම',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 7,
                'code_name_en' => 'Employment',
                'code_name_tm' => 'வேலைவாய்ப்பு',
                'code_name_sn' => 'රැකියාව',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 8,
                'code_name_en' => 'Self Employment/Entrepreneurship',
                'code_name_tm' => 'சுயதொழில்/தொழில்முனைவு',
                'code_name_sn' => 'ස්වයං රැකියා/ව්‍යවසායකත්වය',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 9,
                'code_name_en' => 'OJT placement',
                'code_name_tm' => 'OJT வேலை வாய்ப்பு',
                'code_name_sn' => 'OJT ස්ථානගත කිරීම',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            [
                'code_id' => 10,
                'code_name_en' => 'Others',
                'code_name_tm' => 'மற்றவை',
                'code_name_sn' => 'වෙනත් අය',
                'module' => 'counselling_title',
                'status' => 1,
            ],
            //Notice type
            [
                'code_id' => 1,
                'code_name_en' => 'Career Guidance',
                'code_name_tm' => 'தொழில் வழிகாட்டல் ',
                'code_name_sn' => 'වෘත්තීය මාර්ගෝපදේශනය',
                'module' => 'notice_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Career Platform',
                'code_name_tm' => 'Career Platform',
                'code_name_sn' => 'වෘත්තීය වේදිකාව',
                'module' => 'notice_type',
                'status' => 1,
            ],

            //Content type
            [
                'code_id' => 1,
                'code_name_en' => 'Document',
                'code_name_tm' => 'ஆவணம்',
                'code_name_sn' => 'ලේඛනය',
                'module' => 'content_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Video',
                'code_name_tm' => 'வீடியோ',
                'code_name_sn' => 'වීඩියෝ පටය',
                'module' => 'content_type',
                'status' => 1,
            ],

            //Gender
            [
                'code_id' => 1,
                'code_name_en' => 'Male',
                'code_name_tm' => 'ஆண்',
                'code_name_sn' => 'පිරිමි',
                'module' => 'gender',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Female',
                'code_name_tm' => 'பெண்',
                'code_name_sn' => 'ගැහැණු',
                'module' => 'gender',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'N/A',
                'code_name_tm' => 'N/A',
                'code_name_sn' => 'N/A',
                'module' => 'gender',
                'status' => 1,
            ],

            //Job type
            [
                'code_id' => 1,
                'code_name_en' => 'Permanent',
                'code_name_tm' => 'நிரந்தரமானது',
                'code_name_sn' => 'ස්ථිර',
                'module' => 'job_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Contract',
                'code_name_tm' => 'ஒப்பந்த அடிப்படையிலானது',
                'code_name_sn' => 'කොන්ත්‍රාත් පදනම',
                'module' => 'job_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Temporary',
                'code_name_tm' => 'தற்காலிகமானது',
                'code_name_sn' => 'තාවකාලිකයි',
                'module' => 'job_type',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Internship',
                'code_name_tm' => 'பயிற்சி',
                'code_name_sn' => 'සීමාවාසික පුහුණුව',
                'module' => 'job_type',
                'status' => 1,
            ],
//            [
//                'code_id' => 3,
//                'code_name_en' => 'Part time',
//                'code_name_tm' => 'பகுதி நேரம்',
//                'code_name_sn' => 'අර්ධ කාලීන',
//                'module' => 'job_type',
//                'status' => 1,
//            ],

            //work type
            [
                'code_id' => 1,
                'code_name_en' => 'Full-time',
                'code_name_tm' => 'முழுநேரம்',
                'code_name_sn' => 'පූර්ණ කාලීන',
                'module' => 'work_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Part-time',
                'code_name_tm' => 'பகுதி நேரம்',
                'code_name_sn' => 'අර්ධ කාලීන',
                'module' => 'work_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Shift work',
                'code_name_tm' => 'ஷிப்ட் வேலை',
                'code_name_sn' => 'වැඩ මාරු කරන්න',
                'module' => 'work_type',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Flexible hours',
                'code_name_tm' => 'நெகிழ்வான நேரம்',
                'code_name_sn' => 'නම්‍යශීලී පැය',
                'module' => 'work_type',
                'status' => 1,
            ],

            //Ownership
            [
                'code_id' => 1,
                'code_name_en' => 'Charity',
                'code_name_tm' => 'தொண்டு',
                'code_name_sn' => 'සමාජ සත්කාර',
                'module' => 'ownership',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Government',
                'code_name_tm' => 'அரசு',
                'code_name_sn' => 'රාජ්‍ය',
                'module' => 'ownership',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'NGO',
                'code_name_tm' => 'அரச சார்பற்ற நிறுவனம்',
                'code_name_sn' => 'රාජ්‍ය නොවන සංවිධාන',
                'module' => 'ownership',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Private',
                'code_name_tm' => 'தனியார்',
                'code_name_sn' => 'පෞද්ගලික',
                'module' => 'ownership',
                'status' => 1,
            ],

            //Counselling status
            [
                'code_id' => 1,
                'code_name_en' => 'Request',
                'code_name_tm' => 'கோரிக்கை',
                'code_name_sn' => 'ඉල්ලීම',
                'module' => 'counselling_status',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Confirm',
                'code_name_tm' => 'உறுதிப்படுத்தவும்',
                'code_name_sn' => 'තහවුරු කරන්න',
                'module' => 'counselling_status',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Completed',
                'code_name_tm' => 'பூர்த்திசெய்யப்பட்டது',
                'code_name_sn' => 'සම්පූර්ණ කළා',
                'module' => 'counselling_status',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Cancel',
                'code_name_tm' => 'ரத்து செய்க',
                'code_name_sn' => 'අවලංගු කරන්න',
                'module' => 'counselling_status',
                'status' => 1,
            ],

            //Counselling field
            [
                'code_id' => 1,
                'code_name_en' => 'Career Path',
                'code_name_tm' => 'தொழில் செல்வழி',
                'code_name_sn' => 'වෘත්තීය මාර්ගය',
                'module' => 'counselling_field',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Employment',
                'code_name_tm' => 'வேலைவாய்ப்பு',
                'code_name_sn' => 'රැකියාව',
                'module' => 'counselling_field',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Portfoilio Clinic',
                'code_name_tm' => 'போர்ட்ஃபோலியோ கிளினிக் (Portfoilio Clinic)',
                'code_name_sn' => 'පෝට්ෆෝලිය',
                'module' => 'counselling_field',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'OJT',
                'code_name_tm' => 'OJT',
                'code_name_sn' => 'OJT',
                'module' => 'counselling_field',
                'status' => 1,
            ],

            //Counselling type
            [
                'code_id' => 1,
                'code_name_en' => 'Offline guidance',
                'code_name_tm' => 'அகல்நிலை (offline) வழிகாட்டல்',
                'code_name_sn' => 'offline මාර්ගෝපදේශනය',
                'module' => 'counselling_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Online guidance',
                'code_name_tm' => 'நிகழ்நிலை (online) வழிகாட்டல்',
                'code_name_sn' => 'online මාර්ගෝපදේශනය',
                'module' => 'counselling_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Guidance without reservation',
                'code_name_tm' => 'முன்பதிவு இல்லாமல் வழிகாட்டுதல்',
                'code_name_sn' => 'වෙන් කිරීමකින් තොර මාර්ගෝපදේශනය',
                'module' => 'counselling_type',
                'status' => 1,
            ],

            //Career test type
            [
                'code_id' => 1,
                'code_name_en' => 'Career Interest Test',
                'code_name_tm' => 'தொழில் ஆர்வச் சோதனை',
                'code_name_sn' => 'වෘත්තීය රුචිකත්ව පරීක්ෂණය',
                'module' => 'career_test_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Career Key Test',
                'code_name_tm' => 'தொழில் சோதனை',
                'code_name_sn' => 'වෘත්තීය යතුරු පරීක්ෂණය',
                'module' => 'career_test_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Interest and Ability Test',
                'code_name_tm' => 'ஆர்வம் மற்றும் ஆற்றல் சோதனை',
                'code_name_sn' => 'රුචිකත්වය සහ හැකියාවන් පරීක්ෂණය',
                'module' => 'career_test_type',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Interest, Ability and Personality Test',
                'code_name_tm' => 'ஆர்வம், ஆற்றல் மற்றும் ஆளுமைச் சோதனை',
                'code_name_sn' => 'රුචිකත්වය, හැකියාව සහ පෞරුෂ පරීක්ෂණය',
                'module' => 'career_test_type',
                'status' => 1,
            ],
            //Event type
            [
                'code_id' => 1,
                'code_name_en' => 'Competition',
                'code_name_tm' => 'போட்டி',
                'code_name_sn' => 'තරඟය',
                'module' => 'event_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Job fair',
                'code_name_tm' => 'வேலை கண்காட்சி',
                'code_name_sn' => 'රැකියා පොළ',
                'module' => 'event_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Announcement',
                'code_name_tm' => 'அறிவிப்பு',
                'code_name_sn' => 'නිවේදනය',
                'module' => 'event_type',
                'status' => 1,
            ],
            //Verification method
            [
                'code_id' => 1,
                'code_name_en' => 'E-Mail',
                'code_name_tm' => 'மின்னஞ்சல்',
                'code_name_sn' => 'විද්‍යුත් තැපෑල',
                'module' => 'verification_method',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'SMS',
                'code_name_tm' => 'எஸ்எம்எஸ் (குறுஞ்செய்தி)',
                'code_name_sn' => 'කෙටිපණිවිඩ',
                'module' => 'verification_method',
                'status' => 1,
            ],
            //enterprise_type
            [
                'code_id' => 1,
                'code_name_en' => 'Semi Government',
                'code_name_tm' => 'அரசுசார்ந்த நிறுவனம்',
                'code_name_sn' => 'අර්ධ රාජ්‍ය',
                'module' => 'Enterprise_Type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Private',
                'code_name_tm' => 'தனியார்',
                'code_name_sn' => 'පෞද්ගලික',
                'module' => 'Enterprise_Type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Non-Government',
                'code_name_tm' => 'அரச சார்பற்ற நிறுவனம்',
                'code_name_sn' => 'රාජ්‍ය නොවන',
                'module' => 'Enterprise_Type',
                'status' => 1,
            ],
            [
                'code_id' => 4,
                'code_name_en' => 'Other',
                'code_name_tm' => 'மற்றவை',
                'code_name_sn' => 'වෙනත්',
                'module' => 'Enterprise_Type',
                'status' => 1,
            ],
            [
                'code_id' => 5,
                'code_name_en' => 'Government',
                'code_name_tm' => 'அரசு',
                'code_name_sn' => 'රාජ්‍ය',
                'module' => 'Enterprise_Type',
                'status' => 1,
            ],
             //Job status enum
             [
                'code_id' => 0,
                'code_name_en' => 'Cancelled',
                'code_name_tm' => 'ரத்து செய்யப்பட்டது',
                'code_name_sn' => 'අවලංගු කළා',
                'module' => 'job_status',
                'status' => 1,
            ],
            [
                'code_id' => 1,
                'code_name_en' => 'In Progress',
                'code_name_tm' => 'செயல்பாட்டில் உள்ளது (In Progress)',
                'code_name_sn' => 'ප්රගතියේ',
                'module' => 'job_status',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Completed',
                'code_name_tm' => 'பூர்த்திசெய்யப்பட்டது',
                'code_name_sn' => 'සම්පූර්ණ කළා',
                'module' => 'job_status',
                'status' => 1,
            ],

            //salary_type
            [
                'code_id' => 1,
                'code_name_en' => 'Monthly',
                'code_name_tm' => 'மாதாந்திர',
                'code_name_sn' => 'මාසිකව',
                'module' => 'salary_type',
                'status' => 1,
            ],
            [
                'code_id' => 2,
                'code_name_en' => 'Weekly',
                'code_name_tm' => 'வாரந்தோறும்',
                'code_name_sn' => 'සතිපතා',
                'module' => 'salary_type',
                'status' => 1,
            ],
            [
                'code_id' => 3,
                'code_name_en' => 'Hourly',
                'code_name_tm' => 'மணிநேரம்',
                'code_name_sn' => 'පැයකට වරක්',
                'module' => 'salary_type',
                'status' => 1,
            ],
        ];

        DB::table('code_managements')->insert($data);
    }
}
