<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DivisionalSecretariat;
use App\Models\DivisionalSecretariats;

class DivisionalSecretariatsSeeder extends Seeder
{
    public function run()
    {
        $divisionalSecretariats = [
            ['ds_code' => '1101', 'ds_name' => 'Colombo', 'dist_id' => 'D10'],
            ['ds_code' => '1102', 'ds_name' => 'Dehiwala', 'dist_id' => 'D10'],
            ['ds_code' => '1103', 'ds_name' => 'Homagama', 'dist_id' => 'D10'],
            ['ds_code' => '1104', 'ds_name' => 'Kesbewa', 'dist_id' => 'D10'],
            ['ds_code' => '1105', 'ds_name' => 'Kolonnawa', 'dist_id' => 'D10'],
            ['ds_code' => '1106', 'ds_name' => 'Kotte', 'dist_id' => 'D10'],
            ['ds_code' => '1107', 'ds_name' => 'Maharagama', 'dist_id' => 'D10'],
            ['ds_code' => '1108', 'ds_name' => 'Moratuwa', 'dist_id' => 'D10'],
            ['ds_code' => '1109', 'ds_name' => 'Padukka', 'dist_id' => 'D10'],
            ['ds_code' => '1110', 'ds_name' => 'Ratmalana', 'dist_id' => 'D10'],
            ['ds_code' => '1111', 'ds_name' => 'Seethawaka', 'dist_id' => 'D10'],
            ['ds_code' => '1112', 'ds_name' => 'Thimbirigasyaya', 'dist_id' => 'D10'],
            ['ds_code' => '1113', 'ds_name' => 'Kaduwela', 'dist_id' => 'D10'],
            ['ds_code' => '1301', 'ds_name' => 'Agalawatta', 'dist_id' => 'D11'],
            ['ds_code' => '1302', 'ds_name' => 'Bandaragama', 'dist_id' => 'D11'],
            ['ds_code' => '1303', 'ds_name' => 'Beruwala', 'dist_id' => 'D11'],
            ['ds_code' => '1304', 'ds_name' => 'Bulathsinhala', 'dist_id' => 'D11'],
            ['ds_code' => '1305', 'ds_name' => 'Dodangoda', 'dist_id' => 'D11'],
            ['ds_code' => '1306', 'ds_name' => 'Horana', 'dist_id' => 'D11'],
            ['ds_code' => '1307', 'ds_name' => 'Kalutara', 'dist_id' => 'D11'],
            ['ds_code' => '1308', 'ds_name' => 'Madurawala', 'dist_id' => 'D11'],
            ['ds_code' => '1309', 'ds_name' => 'Millaniya', 'dist_id' => 'D11'],
            ['ds_code' => '1310', 'ds_name' => 'Baduraliya', 'dist_id' => 'D11'],
            ['ds_code' => '1311', 'ds_name' => 'Panadura', 'dist_id' => 'D11'],
            ['ds_code' => '1312', 'ds_name' => 'Mathugama', 'dist_id' => 'D11'],
            ['ds_code' => '1313', 'ds_name' => 'Walallawita', 'dist_id' => 'D11'],
            ['ds_code' => '1314', 'ds_name' => 'Ingiriya', 'dist_id' => 'D11'],
            ['ds_code' => '1201', 'ds_name' => 'Attanagalla', 'dist_id' => 'D12'],
            ['ds_code' => '1202', 'ds_name' => 'Biyagama', 'dist_id' => 'D12'],
            ['ds_code' => '1203', 'ds_name' => 'Jaela', 'dist_id' => 'D12'],
            ['ds_code' => '1204', 'ds_name' => 'Divulapitiya', 'dist_id' => 'D12'],
            ['ds_code' => '1205', 'ds_name' => 'Dompe', 'dist_id' => 'D12'],
            ['ds_code' => '1206', 'ds_name' => 'Gampaha', 'dist_id' => 'D12'],
            ['ds_code' => '1207', 'ds_name' => 'Katana', 'dist_id' => 'D12'],
            ['ds_code' => '1208', 'ds_name' => 'Kelaniya', 'dist_id' => 'D12'],
            ['ds_code' => '1209', 'ds_name' => 'Mahara', 'dist_id' => 'D12'],
            ['ds_code' => '1210', 'ds_name' => 'Meerigama', 'dist_id' => 'D12'],
            ['ds_code' => '1211', 'ds_name' => 'Minuwangoda', 'dist_id' => 'D12'],
            ['ds_code' => '1212', 'ds_name' => 'Negombo', 'dist_id' => 'D12'],
            ['ds_code' => '1213', 'ds_name' => 'Wattala', 'dist_id' => 'D12'],
            ['ds_code' => '3201', 'ds_name' => 'Akuressa', 'dist_id' => 'D13'],
            ['ds_code' => '3202', 'ds_name' => 'Athuraliya', 'dist_id' => 'D13'],
            ['ds_code' => '3203', 'ds_name' => 'Devinuwara', 'dist_id' => 'D13'],
            ['ds_code' => '3204', 'ds_name' => 'Dickwella', 'dist_id' => 'D13'],
            ['ds_code' => '3205', 'ds_name' => 'Hakmana', 'dist_id' => 'D13'],
            ['ds_code' => '3206', 'ds_name' => 'Kamburupitiya', 'dist_id' => 'D13'],
            ['ds_code' => '3207', 'ds_name' => 'Kirinda Puhulwelle', 'dist_id' => 'D13'],
            ['ds_code' => '3208', 'ds_name' => 'Kotapola', 'dist_id' => 'D13'],
            ['ds_code' => '3209', 'ds_name' => 'Malimbada', 'dist_id' => 'D13'],
            ['ds_code' => '3210', 'ds_name' => 'Matara', 'dist_id' => 'D13'],
            ['ds_code' => '3211', 'ds_name' => 'Mulatiyana', 'dist_id' => 'D13'],
            ['ds_code' => '3212', 'ds_name' => 'Pasgoda', 'dist_id' => 'D13'],
            ['ds_code' => '3213', 'ds_name' => 'Patabeddara', 'dist_id' => 'D13'],
            ['ds_code' => '3214', 'ds_name' => 'Thihagoda', 'dist_id' => 'D13'],
            ['ds_code' => '3215', 'ds_name' => 'Weligama', 'dist_id' => 'D13'],
            ['ds_code' => '3216', 'ds_name' => 'Welipitiya', 'dist_id' => 'D13'],
            ['ds_code' => '3101', 'ds_name' => 'Ambalangoda', 'dist_id' => 'D14'],
            ['ds_code' => '3102', 'ds_name' => 'Baddegama', 'dist_id' => 'D14'],
            ['ds_code' => '3103', 'ds_name' => 'Balapitiya', 'dist_id' => 'D14'],
            ['ds_code' => '3104', 'ds_name' => 'Bentota', 'dist_id' => 'D14'],
            ['ds_code' => '3105', 'ds_name' => 'Bope - Poddala', 'dist_id' => 'D14'],
            ['ds_code' => '3106', 'ds_name' => 'Elpitiya', 'dist_id' => 'D14'],
            ['ds_code' => '3107', 'ds_name' => 'Galle Four Gravets', 'dist_id' => 'D14'],
            ['ds_code' => '3108', 'ds_name' => 'Habaraduwa', 'dist_id' => 'D14'],
            ['ds_code' => '3109', 'ds_name' => 'Hikkaduwa', 'dist_id' => 'D14'],
            ['ds_code' => '3110', 'ds_name' => 'Imaduwa', 'dist_id' => 'D14'],
            ['ds_code' => '3111', 'ds_name' => 'Karandeniya', 'dist_id' => 'D14'],
            ['ds_code' => '3112', 'ds_name' => 'Nagoda', 'dist_id' => 'D14'],
            ['ds_code' => '3113', 'ds_name' => 'Neluwa', 'dist_id' => 'D14'],
            ['ds_code' => '3114', 'ds_name' => 'Niyagama', 'dist_id' => 'D14'],
            ['ds_code' => '3115', 'ds_name' => 'Thawalama', 'dist_id' => 'D14'],
            ['ds_code' => '3116', 'ds_name' => 'Weliwitiya - Divitura', 'dist_id' => 'D14'],
            ['ds_code' => '3117', 'ds_name' => 'Yakkalamulla', 'dist_id' => 'D14'],
            ['ds_code' => '3118', 'ds_name' => 'Akmeemana', 'dist_id' => 'D14'],
            ['ds_code' => '3301', 'ds_name' => 'Hambantota', 'dist_id' => 'D15'],
            ['ds_code' => '3302', 'ds_name' => 'Tangalle', 'dist_id' => 'D15'],
            ['ds_code' => '3303', 'ds_name' => 'Ambalantota', 'dist_id' => 'D15'],
            ['ds_code' => '3304', 'ds_name' => 'Weeraketiya', 'dist_id' => 'D15'],
            ['ds_code' => '3305', 'ds_name' => 'Tissamaharamaya', 'dist_id' => 'D15'],
            ['ds_code' => '3306', 'ds_name' => 'Katuwana', 'dist_id' => 'D15'],
            ['ds_code' => '3307', 'ds_name' => 'Angunukolapelessa', 'dist_id' => 'D15'],
            ['ds_code' => '3308', 'ds_name' => 'Beliatta', 'dist_id' => 'D15'],
            ['ds_code' => '3309', 'ds_name' => 'Lunugamwehera', 'dist_id' => 'D15'],
            ['ds_code' => '3310', 'ds_name' => 'Okewela', 'dist_id' => 'D15'],
            ['ds_code' => '3311', 'ds_name' => 'Suriyawewa', 'dist_id' => 'D15'],
            ['ds_code' => '3312', 'ds_name' => 'Walasmulla', 'dist_id' => 'D15'],
            ['ds_code' => '4101', 'ds_name' => 'Delft', 'dist_id' => 'D16'],
            ['ds_code' => '4102', 'ds_name' => 'Velanai', 'dist_id' => 'D16'],
            ['ds_code' => '4103', 'ds_name' => 'Kayts', 'dist_id' => 'D16'],
            ['ds_code' => '4104', 'ds_name' => 'Karainagar', 'dist_id' => 'D16'],
            ['ds_code' => '4105', 'ds_name' => 'Jaffna', 'dist_id' => 'D16'],
            ['ds_code' => '4106', 'ds_name' => 'Nallur', 'dist_id' => 'D16'],
            ['ds_code' => '4107', 'ds_name' => 'Sandilipay', 'dist_id' => 'D16'],
            ['ds_code' => '4108', 'ds_name' => 'Chankanai', 'dist_id' => 'D16'],
            ['ds_code' => '4109', 'ds_name' => 'Uduvil', 'dist_id' => 'D16'],
            ['ds_code' => '4110', 'ds_name' => 'Telippalai', 'dist_id' => 'D16'],
            ['ds_code' => '4111', 'ds_name' => 'Kopay', 'dist_id' => 'D16'],
            ['ds_code' => '4112', 'ds_name' => 'Chavakachcheri', 'dist_id' => 'D16'],
            ['ds_code' => '4113', 'ds_name' => 'Karaveddy', 'dist_id' => 'D16'],
            ['ds_code' => '4114', 'ds_name' => 'Point Pedro', 'dist_id' => 'D16'],
            ['ds_code' => '4115', 'ds_name' => 'Maruthankerny', 'dist_id' => 'D16'],
            ['ds_code' => '4301', 'ds_name' => 'Vavuniya (North)', 'dist_id' => 'D17'],
            ['ds_code' => '4302', 'ds_name' => 'Vavuniya ( South )', 'dist_id' => 'D17'],
            ['ds_code' => '4303', 'ds_name' => 'Vavuniya', 'dist_id' => 'D17'],
            ['ds_code' => '4304', 'ds_name' => 'Vengalaweddikulam', 'dist_id' => 'D17'],
            ['ds_code' => '2301', 'ds_name' => 'Nuwara Eliya', 'dist_id' => 'D18'],
            ['ds_code' => '2302', 'ds_name' => 'Kotmale', 'dist_id' => 'D18'],
            ['ds_code' => '2303', 'ds_name' => 'Ambagamuwa', 'dist_id' => 'D18'],
            ['ds_code' => '2304', 'ds_name' => 'Walapane', 'dist_id' => 'D18'],
            ['ds_code' => '2305', 'ds_name' => 'Hanguranketha', 'dist_id' => 'D18'],
            ['ds_code' => '2201', 'ds_name' => 'Matale', 'dist_id' => 'D19'],
            ['ds_code' => '2202', 'ds_name' => 'Rattota', 'dist_id' => 'D19'],
            ['ds_code' => '2203', 'ds_name' => 'Ukuwela', 'dist_id' => 'D19'],
            ['ds_code' => '2204', 'ds_name' => 'Ambangangakorale', 'dist_id' => 'D19'],
            ['ds_code' => '2205', 'ds_name' => 'Naula', 'dist_id' => 'D19'],
            ['ds_code' => '2206', 'ds_name' => 'Galewela', 'dist_id' => 'D19'],
            ['ds_code' => '2207', 'ds_name' => 'Pallepola', 'dist_id' => 'D19'],
            ['ds_code' => '2208', 'ds_name' => 'Laggala-Pallegame', 'dist_id' => 'D19'],
            ['ds_code' => '2209', 'ds_name' => 'Dambulla', 'dist_id' => 'D19'],
            ['ds_code' => '2210', 'ds_name' => 'Yatawatta', 'dist_id' => 'D19'],
            ['ds_code' => '2211', 'ds_name' => 'Wilgamuwa', 'dist_id' => 'D19'],
            ['ds_code' => '4201', 'ds_name' => 'Mannar Town', 'dist_id' => 'D20'],
            ['ds_code' => '4202', 'ds_name' => 'Nanattan', 'dist_id' => 'D20'],
            ['ds_code' => '4203', 'ds_name' => 'Musali', 'dist_id' => 'D20'],
            ['ds_code' => '4204', 'ds_name' => 'Manthai West', 'dist_id' => 'D20'],
            ['ds_code' => '4205', 'ds_name' => 'Madhu', 'dist_id' => 'D20'],
            ['ds_code' => '2101', 'ds_name' => 'Kandy Gangawata Korale', 'dist_id' => 'D21'],
            ['ds_code' => '2102', 'ds_name' => 'Kundasale', 'dist_id' => 'D21'],
            ['ds_code' => '2103', 'ds_name' => 'Pathadumbara', 'dist_id' => 'D21'],
            ['ds_code' => '2104', 'ds_name' => 'Panwila', 'dist_id' => 'D21'],
            ['ds_code' => '2105', 'ds_name' => 'Yatinuwara', 'dist_id' => 'D21'],
            ['ds_code' => '2106', 'ds_name' => 'Udunuwara', 'dist_id' => 'D21'],
            ['ds_code' => '2107', 'ds_name' => 'Udapalatha', 'dist_id' => 'D21'],
            ['ds_code' => '2108', 'ds_name' => 'Doluwa', 'dist_id' => 'D21'],
            ['ds_code' => '2109', 'ds_name' => 'Pahathahewaheta', 'dist_id' => 'D21'],
            ['ds_code' => '2110', 'ds_name' => 'Delthota', 'dist_id' => 'D21'],
            ['ds_code' => '2111', 'ds_name' => 'Medadumbara', 'dist_id' => 'D21'],
            ['ds_code' => '2112', 'ds_name' => 'Udadumbara', 'dist_id' => 'D21'],
            ['ds_code' => '2113', 'ds_name' => 'Minipe', 'dist_id' => 'D21'],
            ['ds_code' => '2114', 'ds_name' => 'Akurana', 'dist_id' => 'D21'],
            ['ds_code' => '2115', 'ds_name' => 'Poojapitiya', 'dist_id' => 'D21'],
            ['ds_code' => '2116', 'ds_name' => 'Harispattuwa', 'dist_id' => 'D21'],
            ['ds_code' => '2117', 'ds_name' => 'Thumpane', 'dist_id' => 'D21'],
            ['ds_code' => '2118', 'ds_name' => 'Hatharaliyadda', 'dist_id' => 'D21'],
            ['ds_code' => '2119', 'ds_name' => 'Ganga Ihala Korale', 'dist_id' => 'D21'],
            ['ds_code' => '2120', 'ds_name' => 'Pasbage Korale', 'dist_id' => 'D21'],
            ['ds_code' => '2121', 'ds_name' => 'Gampola', 'dist_id' => 'D21'],
            ['ds_code' => '4401', 'ds_name' => 'Puthukudiyrippu', 'dist_id' => 'D22'],
            ['ds_code' => '4402', 'ds_name' => 'Maritimepattu', 'dist_id' => 'D22'],
            ['ds_code' => '4403', 'ds_name' => 'Manthai (East)', 'dist_id' => 'D22'],
            ['ds_code' => '4404', 'ds_name' => 'Thunukkai', 'dist_id' => 'D22'],
            ['ds_code' => '4405', 'ds_name' => 'Oddusuddan', 'dist_id' => 'D22'],
            ['ds_code' => '4501', 'ds_name' => 'Karachchi', 'dist_id' => 'D23'],
            ['ds_code' => '4502', 'ds_name' => 'Poonakari', 'dist_id' => 'D23'],
            ['ds_code' => '4503', 'ds_name' => 'Pachchilaipallai', 'dist_id' => 'D23'],
            ['ds_code' => '4504', 'ds_name' => 'Kandawalai', 'dist_id' => 'D23'],
            ['ds_code' => '5101', 'ds_name' => 'Town Batticaloa', 'dist_id' => 'D25'],
            ['ds_code' => '5102', 'ds_name' => 'Kiran', 'dist_id' => 'D25'],
            ['ds_code' => '5103', 'ds_name' => 'Chenkalady', 'dist_id' => 'D25'],
            ['ds_code' => '5104', 'ds_name' => 'Valaichchenai', 'dist_id' => 'D25'],
            ['ds_code' => '5105', 'ds_name' => 'Vavunatheevu', 'dist_id' => 'D25'],
            ['ds_code' => '5106', 'ds_name' => 'Pattipalai', 'dist_id' => 'D25'],
            ['ds_code' => '5107', 'ds_name' => 'Arayampathy', 'dist_id' => 'D25'],
            ['ds_code' => '5108', 'ds_name' => 'Kaluwanchikudy', 'dist_id' => 'D25'],
            ['ds_code' => '5109', 'ds_name' => 'Kattankudy', 'dist_id' => 'D25'],
            ['ds_code' => '5110', 'ds_name' => 'Eravur Town', 'dist_id' => 'D25'],
            ['ds_code' => '5111', 'ds_name' => 'Oddamavadi', 'dist_id' => 'D25'],
            ['ds_code' => '5112', 'ds_name' => 'Valaichchenai', 'dist_id' => 'D25'],
            ['ds_code' => '5113', 'ds_name' => 'Vellavely', 'dist_id' => 'D25'],
            ['ds_code' => '5114', 'ds_name' => 'Vakarai', 'dist_id' => 'D25'],
            ['ds_code' => '5201', 'ds_name' => 'Dehiaththakandiya', 'dist_id' => 'D26'],
            ['ds_code' => '5202', 'ds_name' => 'Padiyathalawa', 'dist_id' => 'D26'],
            ['ds_code' => '5203', 'ds_name' => 'Mahaoya', 'dist_id' => 'D26'],
            ['ds_code' => '5204', 'ds_name' => 'Uhana', 'dist_id' => 'D26'],
            ['ds_code' => '5205', 'ds_name' => 'Ampara Town (Namal Oya)', 'dist_id' => 'D26'],
            ['ds_code' => '5206', 'ds_name' => 'Damana', 'dist_id' => 'D26'],
            ['ds_code' => '5207', 'ds_name' => 'Lahugala', 'dist_id' => 'D26'],
            ['ds_code' => '5208', 'ds_name' => 'Pottuvil', 'dist_id' => 'D26'],
            ['ds_code' => '5209', 'ds_name' => 'Alayadivembu', 'dist_id' => 'D26'],
            ['ds_code' => '5210', 'ds_name' => 'Irakkamam', 'dist_id' => 'D26'],
            ['ds_code' => '5211', 'ds_name' => 'Addalachchenai', 'dist_id' => 'D26'],
            ['ds_code' => '5212', 'ds_name' => 'Ninthavur', 'dist_id' => 'D26'],
            ['ds_code' => '5213', 'ds_name' => 'Kalamunai - I', 'dist_id' => 'D26'],
            ['ds_code' => '5214', 'ds_name' => 'Navithanveli', 'dist_id' => 'D26'],
            ['ds_code' => '5215', 'ds_name' => 'Thirukkovil', 'dist_id' => 'D26'],
            ['ds_code' => '5216', 'ds_name' => 'Karathivu', 'dist_id' => 'D26'],
            ['ds_code' => '5217', 'ds_name' => 'Sammanthurai', 'dist_id' => 'D26'],
            ['ds_code' => '5218', 'ds_name' => 'Akkaraipaththu', 'dist_id' => 'D26'],
            ['ds_code' => '5219', 'ds_name' => 'Sainthamaruthu', 'dist_id' => 'D26'],
            ['ds_code' => '5301', 'ds_name' => 'Trincomalee Town & Gravets', 'dist_id' => 'D27'],
            ['ds_code' => '5302', 'ds_name' => 'Kuchchaveli', 'dist_id' => 'D27'],
            ['ds_code' => '5303', 'ds_name' => 'Kinniya', 'dist_id' => 'D27'],
            ['ds_code' => '5304', 'ds_name' => 'Thabalangamuwa', 'dist_id' => 'D27'],
            ['ds_code' => '5305', 'ds_name' => 'Morawewa', 'dist_id' => 'D27'],
            ['ds_code' => '5306', 'ds_name' => 'Gomarankadawala', 'dist_id' => 'D27'],
            ['ds_code' => '5307', 'ds_name' => 'Kantale', 'dist_id' => 'D27'],
            ['ds_code' => '5308', 'ds_name' => 'Padavi Siripura', 'dist_id' => 'D27'],
            ['ds_code' => '5309', 'ds_name' => 'Seruvila', 'dist_id' => 'D27'],
            ['ds_code' => '5310', 'ds_name' => 'Muthur', 'dist_id' => 'D27'],
            ['ds_code' => '5311', 'ds_name' => 'Verugal', 'dist_id' => 'D27'],
            ['ds_code' => '7101', 'ds_name' => 'Medawachchiya', 'dist_id' => 'D28'],
            ['ds_code' => '7102', 'ds_name' => 'Ipologama', 'dist_id' => 'D28'],
            ['ds_code' => '7103', 'ds_name' => 'Kebithigollewa', 'dist_id' => 'D28'],
            ['ds_code' => '7104', 'ds_name' => 'Rambewa', 'dist_id' => 'D28'],
            ['ds_code' => '7105', 'ds_name' => 'Thalawa', 'dist_id' => 'D28'],
            ['ds_code' => '7106', 'ds_name' => 'Kekirawa', 'dist_id' => 'D28'],
            ['ds_code' => '7107', 'ds_name' => 'Horowpothana', 'dist_id' => 'D28'],
            ['ds_code' => '7108', 'ds_name' => 'Galenbindunuwewa', 'dist_id' => 'D28'],
            ['ds_code' => '7109', 'ds_name' => 'Galnewa', 'dist_id' => 'D28'],
            ['ds_code' => '7110', 'ds_name' => 'Kahatagasdigiliya', 'dist_id' => 'D28'],
            ['ds_code' => '7111', 'ds_name' => 'Thambuttegama', 'dist_id' => 'D28'],
            ['ds_code' => '7112', 'ds_name' => 'Nachchaduwa', 'dist_id' => 'D28'],
            ['ds_code' => '7113', 'ds_name' => 'Nuwaragam Palatha East', 'dist_id' => 'D28'],
            ['ds_code' => '7114', 'ds_name' => 'Nuwaragam Palatha East Central', 'dist_id' => 'D28'],
            ['ds_code' => '7115', 'ds_name' => 'Mihintale', 'dist_id' => 'D28'],
            ['ds_code' => '7116', 'ds_name' => 'Thirappane', 'dist_id' => 'D28'],
            ['ds_code' => '7117', 'ds_name' => 'Palagala', 'dist_id' => 'D28'],
            ['ds_code' => '7118', 'ds_name' => 'Palugaswewa', 'dist_id' => 'D28'],
            ['ds_code' => '7119', 'ds_name' => 'Nochchiyagama', 'dist_id' => 'D28'],
            ['ds_code' => '7120', 'ds_name' => 'Rajanganaya', 'dist_id' => 'D28'],
            ['ds_code' => '7121', 'ds_name' => 'Mahawilachchiya', 'dist_id' => 'D28'],
            ['ds_code' => '7122', 'ds_name' => 'Padaviya', 'dist_id' => 'D28'],
            ['ds_code' => '7201', 'ds_name' => 'Medirigiriya', 'dist_id' => 'D29'],
            ['ds_code' => '7202', 'ds_name' => 'Lankapura', 'dist_id' => 'D29'],
            ['ds_code' => '7203', 'ds_name' => 'Elahera', 'dist_id' => 'D29'],
            ['ds_code' => '7204', 'ds_name' => 'Hingurakgoda', 'dist_id' => 'D29'],
            ['ds_code' => '7205', 'ds_name' => 'Tamankaduwa', 'dist_id' => 'D29'],
            ['ds_code' => '7206', 'ds_name' => 'Dimbulagala', 'dist_id' => 'D29'],
            ['ds_code' => '7207', 'ds_name' => 'Welikanda', 'dist_id' => 'D29'],
            ['ds_code' => '8101', 'ds_name' => 'Mahiyanganaya', 'dist_id' => 'D30'],
            ['ds_code' => '8102', 'ds_name' => 'Rideemaliyadda', 'dist_id' => 'D30'],
            ['ds_code' => '8103', 'ds_name' => 'Meegahakiwula', 'dist_id' => 'D30'],
            ['ds_code' => '8104', 'ds_name' => 'Kandaketiya', 'dist_id' => 'D30'],
            ['ds_code' => '8105', 'ds_name' => 'Soranathota', 'dist_id' => 'D30'],
            ['ds_code' => '8106', 'ds_name' => 'Badulla', 'dist_id' => 'D30'],
            ['ds_code' => '8107', 'ds_name' => 'Passara', 'dist_id' => 'D30'],
            ['ds_code' => '8108', 'ds_name' => 'Hali Ela', 'dist_id' => 'D30'],
            ['ds_code' => '8109', 'ds_name' => 'Welimada', 'dist_id' => 'D30'],
            ['ds_code' => '8110', 'ds_name' => 'Uva Paranagama', 'dist_id' => 'D30'],
            ['ds_code' => '8111', 'ds_name' => 'Bandarawela', 'dist_id' => 'D30'],
            ['ds_code' => '8112', 'ds_name' => 'Ella', 'dist_id' => 'D30'],
            ['ds_code' => '8113', 'ds_name' => 'Haputale', 'dist_id' => 'D30'],
            ['ds_code' => '8114', 'ds_name' => 'Haldummulla', 'dist_id' => 'D30'],
            ['ds_code' => '8115', 'ds_name' => 'Lunugala', 'dist_id' => 'D30'],
            ['ds_code' => '8201', 'ds_name' => 'Sewanagala', 'dist_id' => 'D31'],
            ['ds_code' => '8202', 'ds_name' => 'Thanamalwila', 'dist_id' => 'D31'],
            ['ds_code' => '8203', 'ds_name' => 'Wellawaya', 'dist_id' => 'D31'],
            ['ds_code' => '8204', 'ds_name' => 'Buttala', 'dist_id' => 'D31'],
            ['ds_code' => '8205', 'ds_name' => 'Moneragala', 'dist_id' => 'D31'],
            ['ds_code' => '8206', 'ds_name' => 'Siyambalanduwa', 'dist_id' => 'D31'],
            ['ds_code' => '8207', 'ds_name' => 'Madulla', 'dist_id' => 'D31'],
            ['ds_code' => '8208', 'ds_name' => 'Bibile', 'dist_id' => 'D31'],
            ['ds_code' => '8209', 'ds_name' => 'Medagama', 'dist_id' => 'D31'],
            ['ds_code' => '8210', 'ds_name' => 'Badalkumbura', 'dist_id' => 'D31'],
            ['ds_code' => '8211', 'ds_name' => 'Kataragama', 'dist_id' => 'D31'],
            ['ds_code' => '9101', 'ds_name' => 'Ratnapura', 'dist_id' => 'D32'],
            ['ds_code' => '9102', 'ds_name' => 'Kuruwita', 'dist_id' => 'D32'],
            ['ds_code' => '9103', 'ds_name' => 'Eheliyagoda', 'dist_id' => 'D32'],
            ['ds_code' => '9104', 'ds_name' => 'Nivithigala', 'dist_id' => 'D32'],
            ['ds_code' => '9105', 'ds_name' => 'Ayagama', 'dist_id' => 'D32'],
            ['ds_code' => '9106', 'ds_name' => 'Pelmadulla', 'dist_id' => 'D32'],
            ['ds_code' => '9108', 'ds_name' => 'Impulpe', 'dist_id' => 'D32'],
            ['ds_code' => '9109', 'ds_name' => 'Kalawana', 'dist_id' => 'D32'],
            ['ds_code' => '9110', 'ds_name' => 'Weligepola', 'dist_id' => 'D32'],
            ['ds_code' => '9111', 'ds_name' => 'Kolonna', 'dist_id' => 'D32'],
            ['ds_code' => '9112', 'ds_name' => 'Embilipitiya', 'dist_id' => 'D32'],
            ['ds_code' => '9113', 'ds_name' => 'Kahawatta', 'dist_id' => 'D32'],
            ['ds_code' => '9114', 'ds_name' => 'Galpotha', 'dist_id' => 'D32'],
            ['ds_code' => '9115', 'ds_name' => 'Opanayaka', 'dist_id' => 'D32'],
            ['ds_code' => '9116', 'ds_name' => 'Godakawela', 'dist_id' => 'D32'],
            ['ds_code' => '9117', 'ds_name' => 'Kiriella', 'dist_id' => 'D32'],
            ['ds_code' => '9118', 'ds_name' => 'Elapatha', 'dist_id' => 'D32'],
            ['ds_code' => '9119', 'ds_name' => 'Balangoda', 'dist_id' => 'D32'],
            ['ds_code' => '9201', 'ds_name' => 'Aranayake', 'dist_id' => 'D33'],
            ['ds_code' => '9202', 'ds_name' => 'Mawanella', 'dist_id' => 'D33'],
            ['ds_code' => '9203', 'ds_name' => 'Rambukkana', 'dist_id' => 'D33'],
            ['ds_code' => '9204', 'ds_name' => 'Kegalle', 'dist_id' => 'D33'],
            ['ds_code' => '9205', 'ds_name' => 'Galigamuwa', 'dist_id' => 'D33'],
            ['ds_code' => '9206', 'ds_name' => 'Warakapola', 'dist_id' => 'D33'],
            ['ds_code' => '9207', 'ds_name' => 'Ruwanwella', 'dist_id' => 'D33'],
            ['ds_code' => '9208', 'ds_name' => 'Yatiyantota', 'dist_id' => 'D33'],
            ['ds_code' => '9209', 'ds_name' => 'Bulathkohupitiya', 'dist_id' => 'D33'],
            ['ds_code' => '9210', 'ds_name' => 'Dehiovita', 'dist_id' => 'D33'],
            ['ds_code' => '9211', 'ds_name' => 'Deraniyagala', 'dist_id' => 'D33'],
            ['ds_code' => '6101', 'ds_name' => 'Giribage', 'dist_id' => 'D35'],
            ['ds_code' => '6102', 'ds_name' => 'Galgamuwa', 'dist_id' => 'D35'],
            ['ds_code' => '6103', 'ds_name' => 'Ehetuwewa', 'dist_id' => 'D35'],
            ['ds_code' => '6104', 'ds_name' => 'Mahawa', 'dist_id' => 'D35'],
            ['ds_code' => '6105', 'ds_name' => 'Ambanpola', 'dist_id' => 'D35'],
            ['ds_code' => '6106', 'ds_name' => 'Kotawehera', 'dist_id' => 'D35'],
            ['ds_code' => '6107', 'ds_name' => 'Rasnayakapura', 'dist_id' => 'D35'],
            ['ds_code' => '6108', 'ds_name' => 'Nikaweratiya', 'dist_id' => 'D35'],
            ['ds_code' => '6109', 'ds_name' => 'Polpithigama', 'dist_id' => 'D35'],
            ['ds_code' => '6110', 'ds_name' => 'Ibbagamuwa', 'dist_id' => 'D35'],
            ['ds_code' => '6111', 'ds_name' => 'Ganewatta', 'dist_id' => 'D35'],
            ['ds_code' => '6112', 'ds_name' => 'Rideegama', 'dist_id' => 'D35'],
            ['ds_code' => '6113', 'ds_name' => 'Mawathagama', 'dist_id' => 'D35'],
            ['ds_code' => '6114', 'ds_name' => 'Mallawapitiya', 'dist_id' => 'D35'],
            ['ds_code' => '6115', 'ds_name' => 'Kurunegala', 'dist_id' => 'D35'],
            ['ds_code' => '6116', 'ds_name' => 'Maspotha', 'dist_id' => 'D35'],
            ['ds_code' => '6117', 'ds_name' => 'Weerambugedara', 'dist_id' => 'D35'],
            ['ds_code' => '6118', 'ds_name' => 'Polgahawela', 'dist_id' => 'D35'],
            ['ds_code' => '6119', 'ds_name' => 'Alawwa', 'dist_id' => 'D35'],
            ['ds_code' => '6120', 'ds_name' => 'Narammala', 'dist_id' => 'D35'],
            ['ds_code' => '6121', 'ds_name' => 'Kuliyapitiya East', 'dist_id' => 'D35'],
            ['ds_code' => '6122', 'ds_name' => 'Kuliyapitiya West', 'dist_id' => 'D35'],
            ['ds_code' => '6123', 'ds_name' => 'Wariyapola', 'dist_id' => 'D35'],
            ['ds_code' => '6124', 'ds_name' => 'Panduwasnuwara East', 'dist_id' => 'D35'],
            ['ds_code' => '6125', 'ds_name' => 'Bamunukotuwa', 'dist_id' => 'D35'],
            ['ds_code' => '6126', 'ds_name' => 'Panduwasnuwara West', 'dist_id' => 'D35'],
            ['ds_code' => '6127', 'ds_name' => 'Bingiriya', 'dist_id' => 'D35'],
            ['ds_code' => '6128', 'ds_name' => 'Udubaddawa', 'dist_id' => 'D35'],
            ['ds_code' => '6129', 'ds_name' => 'Kobeigane', 'dist_id' => 'D35'],
            ['ds_code' => '6130', 'ds_name' => 'Pannala', 'dist_id' => 'D35'],
            ['ds_code' => '6131', 'ds_name' => 'Maho', 'dist_id' => 'D35'],
            ['ds_code' => '6201', 'ds_name' => 'Wennappuwa', 'dist_id' => 'D36'],
            ['ds_code' => '6202', 'ds_name' => 'Naththandiya', 'dist_id' => 'D36'],
            ['ds_code' => '6203', 'ds_name' => 'Chilaw', 'dist_id' => 'D36'],
            ['ds_code' => '6204', 'ds_name' => 'Arachchikattuwa', 'dist_id' => 'D36'],
            ['ds_code' => '6205', 'ds_name' => 'Puttalam', 'dist_id' => 'D36'],
            ['ds_code' => '6206', 'ds_name' => 'Kalpitiya', 'dist_id' => 'D36'],
            ['ds_code' => '6207', 'ds_name' => 'Wanathawilluwa', 'dist_id' => 'D36'],
            ['ds_code' => '6208', 'ds_name' => 'Karuwalagaswewa', 'dist_id' => 'D36'],
            ['ds_code' => '6209', 'ds_name' => 'Nawagaththegama', 'dist_id' => 'D36'],
            ['ds_code' => '6210', 'ds_name' => 'Anamaduwa', 'dist_id' => 'D36'],
            ['ds_code' => '6211', 'ds_name' => 'Mahawewa', 'dist_id' => 'D36'],
            ['ds_code' => '6212', 'ds_name' => 'Madampe', 'dist_id' => 'D36'],
            ['ds_code' => '6213', 'ds_name' => 'Pallama', 'dist_id' => 'D36'],
            ['ds_code' => '6214', 'ds_name' => 'Mahakumbukkadawala', 'dist_id' => 'D36'],
            ['ds_code' => '6215', 'ds_name' => 'Dankotuwa', 'dist_id' => 'D36'],
            ['ds_code' => '6216', 'ds_name' => 'Mundel', 'dist_id' => 'D36'],
        ];

        foreach ($divisionalSecretariats as $secretariat) {
            DivisionalSecretariats::create($secretariat);
        }
    }
}
