sonar.projectKey=Career-Srilanka
sonar.projectName=Career-Srilanka
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://10.0.0.12:9000
sonar.token=sqp_8fecfb8cadb24a607685f77e595979abe1b8cd9c
