import preset from '../../../../vendor/filament/filament/tailwind.config.preset'

export default {
    presets: [preset],
    mode: 'jit',
    content: [
        './resources/views/filament/**/*.blade.php',
        './resources/views/admin/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './vendor/kenepa/translation-manager/resources/**/*.blade.php',
    ],
    theme: {
        screens: {
            xs: '480px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px'
        },
        extend: {
            colors: {
                primary: `var(--primary)`,
                'main-bg': `#f8f9fb`,

                'primary-1': `var(--primary-1)`,
                'primary-2': `var(--primary-2)`,
                'primary-3': `var(--primary-3)`,
                'primary-4': `var(--primary-4)`,
                'primary-5': `var(--primary-5)`,
                'primary-6': `var(--primary-6)`,
                'primary-7': `var(--primary-7)`,
                'primary-8': `var(--primary-8)`,

                'grey-0': `var(--grey-0)`,
                'grey-1': `var(--grey-1)`,
                'grey-2': `var(--grey-2)`,
                'grey-3': `var(--grey-3)`,
                'grey-4': `var(--grey-4)`,
                'grey-5': `var(--grey-5)`,
                'grey-6': `var(--grey-6)`,
                'grey-7': `var(--grey-7)`,
                'grey-8': `var(--grey-8)`,
                'grey-10': `var(--grey-10)`,

                'hsl-80': `hsl(0, 0%, 80%)`,

                'green-1': `var(--green-1)`,
                'green-2': `var(--green-2)`,
                'green-3': `var(--green-3)`,
                'green-4': `var(--green-4)`,
                'green-5': `var(--green-5)`,
                'green-6': `var(--green-6)`,

                'red-1': `var(--red-1)`,
                'red-2': `var(--red-2)`,
                'red-3': `var(--red-3)`,
                'red-4': `var(--red-4)`,
                'red-5': `var(--red-5)`,
                'red-6': `var(--red-6)`,

                'yellow-1': `var(--yellow-1)`,
                'yellow-2': `var(--yellow-2)`,
                'yellow-3': `var(--yellow-3)`,

                dark: `var(--dark)`,
                'text-secondary': `var(--text-secondary)`,
            },
            padding: {
                '29': '29px',
                '16': '64px',
                '10': '40px'
            },
            borderRadius: {
                none: "0px",
                sm: "2px",
                DEFAULT: "4px",
                md: "6px",
                lg: "8px",
                xl: "12px",
                "2xl": "16px",
                "3xl": "24px",
                full: "9999px",
            },
            columns: {
                auto: "auto",
                1: "1",
                2: "2",
                3: "3",
                4: "4",
                5: "5",
                6: "6",
                7: "7",
                8: "8",
                9: "9",
                10: "10",
                11: "11",
                12: "12",
                "3xs": "256px",
                "2xs": "288px",
                xs: "320px",
                sm: "384px",
                md: "448px",
                lg: "512px",
                xl: "576px",
                "2xl": "672px",
                "3xl": "768px",
                "4xl": "896px",
                "5xl": "1024px",
                "6xl": "1152px",
                "7xl": "1280px",
            },
            fontSize: {
                xs: ["12px", { lineHeight: "16px" }],
                sm: ["14px", { lineHeight: "20px" }],
                base: ["16px", { lineHeight: "24px" }],
                lg: ["18px", { lineHeight: "28px" }],
                xl: ["20px", { lineHeight: "28px" }],
                "2xl": ["24px", { lineHeight: "32px" }],
                "3xl": ["30px", { lineHeight: "36px" }],
                "4xl": ["36px", { lineHeight: "36px" }],
                "5xl": ["48px", { lineHeight: "1" }],
                "6xl": ["60px", { lineHeight: "1" }],
                "7xl": ["72px", { lineHeight: "1" }],
                "8xl": ["96px", { lineHeight: "1" }],
                "9xl": ["144px", { lineHeight: "1" }],
            },
            lineHeight: {
                none: "1",
                tight: "1.25",
                snug: "1.375",
                normal: "1.5",
                relaxed: "1.625",
                loose: "2",
                3: "12px",
                4: "16px",
                5: "20px",
                6: "24px",
                7: "28px",
                8: "32px",
                9: "36px",
                10: "40px",
            },
            maxWidth: ({ theme, breakpoints }) => ({
                none: "none",
                0: "0px",
                xs: "320px",
                sm: "384px",
                md: "448px",
                lg: "512px",
                xl: "576px",
                "2xl": "672px",
                "3xl": "768px",
                "4xl": "896px",
                "5xl": "1024px",
                "6xl": "1152px",
                "7xl": "1280px",
                full: "100%",
                min: "min-content",
                max: "max-content",
                fit: "fit-content",
                prose: "65ch",
                ...breakpoints(theme("screens")),
            }),
            spacing: {
                px: "1px",
                0: "0",
                0.5: "2px",
                1: "4px",
                1.5: "6px",
                2: "8px",
                2.5: "10px",
                3: "12px",
                3.5: "14px",
                4: "16px",
                5: "20px",
                6: "24px",
                7: "28px",
                8: "32px",
                9: "36px",
                10: "40px",
                11: "44px",
                12: "48px",
                14: "56px",
                16: "64px",
                20: "80px",
                24: "96px",
                28: "112px",
                32: "128px",
                36: "144px",
                40: "160px",
                44: "176px",
                48: "192px",
                52: "208px",
                56: "224px",
                60: "240px",
                64: "256px",
                72: "288px",
                80: "320px",
                96: "384px",
            },
        },
    },
}
